
[global]
type=global
user_agent=Asterisk-3CX-AI


[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[3cx-auth]
type=auth
auth_type=userpass
username=pUYAek4e30
password=yLdyvD8TC2

[3cx-aor]
type=aor
contact=sip:digitalregenesys.elastix.com:5060

[3cx]
type=endpoint

transport=transport-udp

context=from-3cx

disallow=all
allow=ulaw
outbound_auth=3cx-auth

auth=3cx-auth
aors=3cx-aor

from_user=900
from_domain=digitalregenesys.elastix.com

direct_media=no

[3cx-reg]
type=registration

transport=transport-udp

outbound_auth=3cx-auth

server_uri=sip:digitalregenesys.elastix.com:5060

client_uri=sip:pUYAek4e30@digitalregenesys.elastix.com

contact_user=900

expiration=300
retry_interval=60